### ISSUE TITLE
Refactor the auction bit of the codebase

### ISSUE THREAD

**Issue by Captainmango** [Captainmango/auctionite-app#11]
Given I have got the basics of the auction domain sorted
When I want to move on to the next bit
Then I should have a codebase I can forget about

Refactor the routes so they make sense.
Validations on preconditions?
Tidy everything up and make it nice. Think about using lib rather than having everything in controllers (not sure how possible this is tbh)

**Comment by EngineeringEd** [comment]
Changelist:

- Refactor MoneyAware to use define_method to dry up models that use it
- Refactor routes to make sense. Routes that require sign on should be in their own namespace
- Refactor CRUD routes. Should be different from normal read routes. e.g. lots should be accessible to everyone but items and your lots should only be accessible by the owning user
- Create more domain models/concerns and pull code that is likely to duplicate into them (assigning users to things)
- If I feel like it, spend time on styling using PicoCSS
